name: resume
description: resume

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_bloc: ^8.0.1
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^9.2.0
  logger: ^1.1.0
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_annotation: ^4.4.0
  freezed: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true